from sqlalchemy.orm import Session

from app.models.restoration import (
    Difficulty,
    FragmentCategory,
    QuestionType,
    RestorationChapter,
    RestorationFragment,
    RestorationDiagnostic,
    RestorationNode,
)


chapters_metadata = [
    {"chapter_id": 1,  "name": "文字之源",   "alias": "《说文解字》",     "difficulty": "easy",   "description": "中国第一部系统的字书，文字学的古典"},
    {"chapter_id": 2,  "name": "阴阳之书",   "alias": "《周易》",         "difficulty": "easy",   "description": "中国古代的占卜哲学著作，群经之首"},
    {"chapter_id": 3,  "name": "上古之书",   "alias": "《尚书》",         "difficulty": "easy",   "description": "中国最古的记言的历史，政治文献汇编"},
    {"chapter_id": 4,  "name": "诗之源头",   "alias": "《诗经》",         "difficulty": "easy",   "description": "中国第一部诗歌总集，诗三百篇"},
    {"chapter_id": 5,  "name": "礼乐之典",   "alias": "三《礼》",         "difficulty": "medium", "description": "《周礼》《仪礼》《礼记》，中国古代礼制经典"},
    {"chapter_id": 6,  "name": "春秋笔法",   "alias": "《春秋》三传",     "difficulty": "medium", "description": "《左传》《公羊传》《穀梁传》，编年史经典"},
    {"chapter_id": 7,  "name": "圣贤之书",   "alias": "四书",             "difficulty": "medium", "description": "《大学》《中庸》《论语》《孟子》，儒家核心经典"},
    {"chapter_id": 8,  "name": "纵横之策",   "alias": "《战国策》",       "difficulty": "medium", "description": "记载战国时期策士言行的国别体史书"},
    {"chapter_id": 9,  "name": "史家双璧",   "alias": "《史记》《汉书》", "difficulty": "hard",   "description": "纪传体史书的开山之作与断代史典范"},
    {"chapter_id": 10, "name": "百家争鸣",   "alias": "诸子",             "difficulty": "hard",   "description": "春秋战国时期诸子百家思想的集中体现"},
    {"chapter_id": 11, "name": "楚辞汉赋",   "alias": "辞赋",             "difficulty": "hard",   "description": "屈原楚辞开创浪漫主义，汉赋铺陈华美"},
    {"chapter_id": 12, "name": "诗之江河",   "alias": "诗",               "difficulty": "hard",   "description": "从汉乐府到唐诗宋词，中国诗歌的灿烂长河"},
    {"chapter_id": 13, "name": "文之脉络",   "alias": "文",               "difficulty": "hard",   "description": "从先秦散文到唐宋古文运动，中国散文发展脉络"},
]


CHAPTERS_DATA = {
    1: {
        "era_quote": "东汉和帝时，有个许慎，作了一部《说文解字》。这是一部划时代的字书。",
        "positioning": "文字学的古典，一切古典的工具或门径",
        "archive_summary": "《说文解字》由东汉许慎编撰，是中国第一部系统的字书。全书收录九千字，分属五百四十部首，分析偏旁，定出部首，每字都有说解。它意在帮助人通读古书，是文字学的古典，又是一切古典的工具或门径。书中还系统阐述了造字和用字的六个条例——六书。",
        "archive_impact": "《说文解字》奠定了中国文字学的基础，其部首编排法影响后世字典编纂千余年。六书理论成为分析汉字构造的经典框架，至今仍是汉字教学与研究的重要工具。",
        "fragments": [
            ("东汉和帝时期，许慎历时二十余年编成《说文解字》，这是中国第一部系统分析汉字字形和考究字源的字书。", FragmentCategory.era),
            ("秦始皇统一文字，命李斯等人制定小篆为标准字体，结束了战国时期'言语异声，文字异形'的混乱局面。", FragmentCategory.era),
            ("许慎，字叔重，汝南召陵人，曾任太尉府祭酒，师事贾逵，博通经籍，时人誉之'五经无双许叔重'。", FragmentCategory.author),
            ("'六书'指象形、指事、会意、形声、转注、假借，是古人分析汉字构造和使用方法而归纳出来的六种条例。", FragmentCategory.content),
            ("形声字由形旁和声旁组成，形旁表示意义类别，声旁表示读音，如'江''河'二字，'水'是形，'工''可'是声。", FragmentCategory.content),
            ("《说文解字》采用部首编排法，将汉字按偏旁部首分类，开创了后世字典编纂的基本体例。", FragmentCategory.style),
            ("《说文解字》是中国文字学的奠基之作，历代学者不断为之作注，最著名的有清代段玉裁的《说文解字注》。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "《说文解字》的作者是哪位学者？",
                "options": ["许慎", "班固", "郑玄", "司马迁"],
                "correct_answer": "许慎",
                "hint": "东汉和帝时的学者，字叔重，被誉为'五经无双'。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "《说文解字》将汉字分为多少个部首？",
                "options": ["214部", "540部", "100部", "360部"],
                "correct_answer": "540部",
                "hint": "全书九千余字分属五百四十部首，这是许慎首创的部首编排法。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "造字和用字的六个条例称为'______'，包括象形、指事、会意、形声、转注、假借。",
                "options": None,
                "correct_answer": "六书",
                "hint": "许慎在书中系统阐述了这六种汉字构造条例。",
            },
        ],
        "nodes": [
            "甲骨文：殷商时期刻在龟甲兽骨上的文字，是中国已知最早的成熟文字体系。",
            "金文：商周时期铸刻在青铜器上的文字，又称钟鼎文，比甲骨文更加规整。",
            "小篆：秦始皇统一文字后推行的标准字体，笔画圆转，结构匀称。",
            "隶书：由小篆简化演变而来，笔画由圆转变为方折，书写更加便捷。",
            "楷书：由隶书演变而来，笔画平直，结构方正，成为后世通用的标准字体。",
            "行书与草书：行书介于楷书与草书之间，草书则更加简省奔放，便于快速书写。",
        ],
    },
    2: {
        "era_quote": "八卦相传是伏羲氏画的……《周易》里的一张画，是一张排列得整整齐齐的方阵。",
        "positioning": "群经之首，中国古代占卜哲学的源头",
        "archive_summary": "《周易》是中国古代的占卜哲学著作，相传八卦为伏羲所画，后重叠为六十四卦。殷周之际，卜筮材料被编成册子，形成卦辞和爻辞。战国末期，儒家受道家、阴阳家影响，给卦爻辞作新解释，形成《易传》。汉代又发现《说卦》《序卦》《杂卦》等，合称'十翼'。",
        "archive_impact": "《周易》被尊为'群经之首'，其阴阳变化、刚柔相济的哲学思想深刻影响了中国传统文化。儒家从中阐发哲学义理，民间则延续其卜筮传统，两种用法流传至今。",
        "fragments": [
            ("八卦相传是伏羲氏所画，每个符号代表一种自然事物：乾为天，坤为地，坎为水，离为火，震为雷，艮为山，巽为风，兑为泽。", FragmentCategory.era),
            ("殷周之际，卜筮用的兽骨和龟甲数量繁多，有人将其编成册子以便检阅，这些材料上的记录就是卦辞和爻辞的来源。", FragmentCategory.era),
            ("《周易》的卦辞和爻辞形成于殷周之际，经过长期积累，并非一人一时之作。", FragmentCategory.author),
            ("八卦两两重叠，便成六十四卦，每卦有六画，每一画称为一爻，卦辞解释整个卦，爻辞解释每一爻。", FragmentCategory.content),
            ("战国末期，儒家受道家、阴阳家影响，给卦爻辞作新解释，形成《易传》，包括《彖辞》《象辞》《文言》《系辞》等。", FragmentCategory.content),
            ("儒家讲《周易》重视其哲学意义，讲阴阳变化、刚柔相济；民众用《周易》则延续卜筮算命的传统。", FragmentCategory.style),
            ("'天行健，君子以自强不息''地势坤，君子以厚德载物'等名句，成为中华民族精神的重要象征。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "相传八卦是由谁画的？",
                "options": ["黄帝", "伏羲氏", "周文王", "孔子"],
                "correct_answer": "伏羲氏",
                "hint": "上古圣王，他看见了龙马负图而出，据此画出八卦。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "《易传》中《说卦》《序卦》《杂卦》与之前的五种传合称什么？",
                "options": ["九传", "十翼", "八篇", "七录"],
                "correct_answer": "十翼",
                "hint": "这十种传文像鸟的十只翅膀，辅助《周易》飞翔。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "八卦中代表天的符号是______，代表地的符号是坤。",
                "options": None,
                "correct_answer": "乾",
                "hint": "乾为天，坤为地，这是八卦中最基本的两个符号。",
            },
        ],
        "nodes": [
            "伏羲画八卦：上古伏羲氏观察天地万物，画出八卦符号，奠定《周易》基础。",
            "文王演周易：周文王被囚羑里，将八卦重叠为六十四卦，并作卦辞。",
            "周公作爻辞：周公旦为六十四卦的三百八十四爻分别作爻辞，完善《周易》经文。",
            "孔子作十翼：孔子及其后学为《周易》作传，阐发其哲学义理，形成《易传》。",
            "汉代易学兴盛：汉代设立《周易》博士，象数之学大兴，出现多家易学流派。",
            "宋明理学阐发：程颐作《易传》，朱熹作《周易本义》，从理学角度重新诠释《周易》。",
        ],
    },
    3: {
        "era_quote": "《尚书》是中国最古的记言的历史。所谓记言，其实也是记事，不过是一种特别的方式罢了。",
        "positioning": "中国最古的记言历史，政治文献之祖",
        "archive_summary": "《尚书》是中国最古的记言的历史，包括虞、夏、商、周四代，大部分是号令，小部分是君臣相告的话。秦始皇焚书后，汉初伏生壁藏《尚书》，仅存二十九篇，是为今文《尚书》。后又有古文《尚书》之争，直到清代阎若璩才辨明真伪。",
        "archive_impact": "《尚书》保存了商周两代的诰命，是研究中国古代政治、法律、宗教、思想的重要史料。其'协和万邦''民惟邦本'等思想，成为中国政治哲学的核心命题。",
        "fragments": [
            ("《尚书》包括虞、夏、商、周四代，大部分是向大众宣布的号令，小部分是君臣相告的话。", FragmentCategory.era),
            ("秦始皇烧天下诗书，《尚书》遭了殃，汉初秦博士伏生壁藏一部，后来只残存二十九篇。", FragmentCategory.era),
            ("伏生是秦博士，汉初已九十多岁，由女儿转述，晁错记录下来，这便是今文《尚书》的来历。", FragmentCategory.author),
            ("《尚书》是中国最古的记言历史，记事比较间接，记言比较直接，大部分照说的话写下来。", FragmentCategory.content),
            ("今文《尚书》二十九篇中，大部分是商周两代的诰命，是研究古代政治、法律、宗教的重要史料。", FragmentCategory.content),
            ("《尚书》文字古朴艰涩，佶屈聱牙，韩愈说它'周诰殷盘，佶屈聱牙'，是古文中难读的代表。", FragmentCategory.style),
            ("'民惟邦本，本固邦宁''满招损，谦受益'等名句出自《尚书》，成为千古传诵的格言。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "汉初伏生壁藏的《尚书》残存多少篇？",
                "options": ["二十九篇", "五十八篇", "二十五篇", "十六篇"],
                "correct_answer": "二十九篇",
                "hint": "伏生壁藏《尚书》，后来只残存二十九篇，这就是今文《尚书》。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "哪位学者证明了梅赜所献古文《尚书》中的二十五篇是伪作？",
                "options": ["顾炎武", "黄宗羲", "阎若璩", "王夫之"],
                "correct_answer": "阎若璩",
                "hint": "清代学者，著有《古文尚书疏证》，以严密考证辨明真伪。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "《尚书》的文体有典、谟、训、诰、誓、______六种。",
                "options": None,
                "correct_answer": "命",
                "hint": "《尚书》中君主对臣下的任命之词称为此体。",
            },
        ],
        "nodes": [
            "上古记言：虞夏商周时期，史官记录君臣言论，形成最早的记言历史。",
            "孔子编订：孔子整理古代文献，将上古史料编为《尚书》，作为教材传授弟子。",
            "秦火劫难：秦始皇焚书坑儒，《尚书》几乎亡佚，伏生壁藏才得以保存。",
            "今文传承：汉初伏生传授今文《尚书》，晁错记录，设立博士官，成为官方经典。",
            "古文发现：汉武帝末年，孔子壁中发现古文《尚书》，引发今古文之争。",
            "真伪辨明：清代阎若璩作《古文尚书疏证》，考证出梅赜所献二十五篇为伪作。",
        ],
    },
    4: {
        "era_quote": "诗的源头是歌谣。上古时候，没有文字，只有唱的歌谣，没有写的诗。",
        "positioning": "中国第一部诗歌总集，现实主义源头",
        "archive_summary": "《诗经》是中国第一部诗歌总集，收录了西周初年到春秋中叶的诗歌三百零五篇。诗的源头是歌谣，由乐工搜集整理，分为'风''雅''颂'三大类，表现手法有'赋''比''兴'三种。孔子以后，'诗三百'成为儒家六经之一，对中国文学产生了深远影响。",
        "archive_impact": "《诗经》开创了中国现实主义的文学传统，其'风、雅、颂'的分类和'赋、比、兴'的表现手法，成为后世诗歌创作的基本范式。'诗言志'的传统影响中国文学数千年。",
        "fragments": [
            ("上古时没有文字，只有唱的歌谣，没有写的诗。歌谣越唱越多，存在人的记忆里，后来由乐工记录下来。", FragmentCategory.era),
            ("春秋时各国都养着一班乐工，太师们搜集本国和别国的乐歌，带着乐谱，当时通称作'诗三百'。", FragmentCategory.era),
            ("《诗经》的编订相传与孔子有关，孔子从三千余篇古诗中删定为三百零五篇，用于教化弟子。", FragmentCategory.author),
            ("《诗经》分为'风''雅''颂'三大类：风是各地方的乐歌，雅是正统的乐歌，颂是宗庙祭祀的乐歌。", FragmentCategory.content),
            ("《诗经》的表现手法有'赋''比''兴'三种：赋是直陈其事，比是借物喻人，兴是托物起兴。", FragmentCategory.content),
            ("《诗经》以四言为主，句式整齐，重章叠句，反复咏叹，具有鲜明的音乐性和节奏感。", FragmentCategory.style),
            ("《诗经》成为儒家六经之一，孔子说'不学诗，无以言'，将其作为教育和外交的重要工具。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "《诗经》分为哪三大类？",
                "options": ["赋比兴", "风雅颂", "诗词曲", "乐府歌"],
                "correct_answer": "风雅颂",
                "hint": "风是地方乐歌，雅是正统乐歌，颂是宗庙祭祀乐歌。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "《诗经》的表现手法'赋、比、兴'中，'比'是什么意思？",
                "options": ["直陈其事", "借物喻人", "托物起兴", "反复咏叹"],
                "correct_answer": "借物喻人",
                "hint": "朱熹解释'比者，以彼物比此物也'。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "孔子说：'不学______，无以言。'",
                "options": None,
                "correct_answer": "诗",
                "hint": "孔子非常重视这部诗歌总集的教育功能。",
            },
        ],
        "nodes": [
            "上古歌谣：上古时期没有文字，人们以歌谣表达情感，这是诗歌的最早源头。",
            "采诗制度：周代设立采诗之官，到民间搜集歌谣，以观风俗、知得失。",
            "太师整理：各国乐工太师搜集、整理、改编歌谣，形成三百余篇的唱本。",
            "孔子删订：孔子从众多古诗中精选三百零五篇，作为儒家教材。",
            "汉立博士：汉武帝设立五经博士，《诗经》成为官方经典，毛亨、郑玄等为之作注。",
            "朱熹集传：南宋朱熹作《诗集传》，以理学观点重新解释《诗经》，影响后世数百年。",
        ],
    },
    5: {
        "era_quote": "儒家有拿礼来包罗万象的野心，他们认礼为治乱的根本。",
        "positioning": "中国古代礼制经典，社会秩序的规范",
        "archive_summary": "三礼指《周礼》《仪礼》《礼记》。《仪礼》是宗教仪式、风俗习惯的记录，相传是周公所作，全书十七篇。《周礼》是政治制度的记述，原称《周官》，分天官、地官等六部分。《礼记》是儒家杂述礼制、礼意的文章，由汉代儒生辑录而成。",
        "archive_impact": "三礼是中国古代礼制文化的核心经典，记录了古代社会的政治制度、宗教仪式和风俗习惯。礼乐教化的思想深深影响了中国人的伦理观念和社会行为规范。",
        "fragments": [
            ("相传周公制礼作乐，整理了前代的礼乐制度，加以系统的组织，奠定了周代礼乐文明的基础。", FragmentCategory.era),
            ("周代的礼乐制度到春秋时已渐渐崩坏，诸侯争霸，僭越礼制的事时常发生，孔子一生致力于恢复周礼。", FragmentCategory.era),
            ("《仪礼》相传是周公所作，但大概是战国初年儒家的作品，全书十七篇，记载冠、婚、丧、祭等礼仪的详细程序。", FragmentCategory.author),
            ("《仪礼》是礼的本经，主要记载各种礼仪的具体程序；《周礼》记述理想的官制体系；《礼记》阐发礼的意义。", FragmentCategory.content),
            ("礼的作用是'节'，是节制人的欲望，使人的行为合乎规矩；乐的作用是和，调和人的情感。", FragmentCategory.content),
            ("三礼的文字古奥难读，尤其是《仪礼》，记载礼仪程序极为繁琐细致，需要借助注疏才能理解。", FragmentCategory.style),
            ("儒家以礼为治乱的根本，认为礼是社会的秩序、人与人的关系的规范，人人都应该遵守。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "三礼中哪一部是礼的本经，主要记载各种礼仪的具体程序？",
                "options": ["《周礼》", "《仪礼》", "《礼记》", "《礼论》"],
                "correct_answer": "《仪礼》",
                "hint": "这部书全书十七篇，记载冠、婚、丧、祭等礼仪的详细程序。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "《周礼》全书分为哪六个部分？",
                "options": ["仁义礼智信孝", "天地春夏秋冬", "天官地官春官夏官秋官冬官", "诗书礼乐易春秋"],
                "correct_answer": "天官地官春官夏官秋官冬官",
                "hint": "这部书原称《周官》，记述了理想的官制体系。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "孔子说：'克己复礼为______。'",
                "options": None,
                "correct_answer": "仁",
                "hint": "孔子认为约束自己、使言行符合礼的规范，就是仁德的表现。",
            },
        ],
        "nodes": [
            "周公制礼：相传周公整理前代礼乐，建立系统的礼乐制度，奠定周代文明基础。",
            "春秋崩坏：周王室衰微，诸侯僭越礼制，礼崩乐坏，孔子立志恢复周礼。",
            "仪礼成书：战国初年儒家整理礼仪程序，编成《仪礼》十七篇，成为礼的本经。",
            "周官编纂：战国时人根据现实制度与儒家理想，编纂《周礼》，记述六官体系。",
            "礼记辑录：汉代儒生辑录儒家论礼文章，编成《礼记》，阐发礼的深层意义。",
            "四书抽出：南宋朱熹从《礼记》中抽出《大学》《中庸》，与《论语》《孟子》合称四书。",
        ],
    },
    6: {
        "era_quote": "《春秋》只是鲁国史官的旧文，孔子不曾掺进手去。孔子那时已成了一个权威，他删订的史书，自然被尊为经典。",
        "positioning": "编年史之祖，微言大义的典范",
        "archive_summary": "《春秋》是鲁国史官的旧文，相传由孔子编订，文字极简，只有大纲没有细节。解释《春秋》的书有三部，称为'三传'：《左传》以叙事为主，《公羊传》《穀梁传》以解经为主。三传中《左传》文学价值最高，善于描写战争和刻画人物。",
        "archive_impact": "《春秋》开创了中国编年体史书的先河，其'微言大义'的书法成为后世史书褒贬人物、评判是非的典范。《左传》的叙事艺术更是中国古代散文的杰作，影响深远。",
        "fragments": [
            ("'春秋'是古代记事史书的通称，各国有各国的春秋，但传下的只有一部《鲁春秋》。", FragmentCategory.era),
            ("孔子周游列国不能用世，回到家乡整理古代文献，删订《诗》《书》，修起《春秋》来。", FragmentCategory.era),
            ("《左传》相传是鲁国人左丘明所作，以《春秋》为纲，增补大量史实，是一部详尽的编年史。", FragmentCategory.author),
            ("《春秋》的文字极简单，只有大纲没有细节，记载战争有'伐''侵''战''围''入''灭'等不同字眼。", FragmentCategory.content),
            ("三传中《左传》以叙事为主，最为详博；《公羊传》《穀梁传》以解经为主，重在义理。", FragmentCategory.content),
            ("《左传》善于描写战争，如秦晋殽之战、晋楚城濮之战，都写得惊心动魄，是中国古代散文的杰作。", FragmentCategory.style),
            ("汉代《春秋》成为五经之一，设立博士官传授，形成了专门的'春秋学'，影响中国古代政治法律伦理。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "三传中哪一部以叙事为主，文学价值最高？",
                "options": ["《公羊传》", "《穀梁传》", "《左传》", "《春秋传》"],
                "correct_answer": "《左传》",
                "hint": "这部书相传是左丘明所作，善于描写战争和刻画人物。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "《春秋》记载战争时，用哪个字表示有钟鼓的正式战争？",
                "options": ["侵", "伐", "入", "灭"],
                "correct_answer": "伐",
                "hint": "《春秋》书法讲究，不同字眼代表不同意义的军事行动。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "《春秋》的书法体现了儒家的褒贬之意，所谓'一字之褒，荣于华衮；一字之贬，严于______'。",
                "options": None,
                "correct_answer": "斧钺",
                "hint": "华衮是礼服，此物是刑具，形容褒贬的分量极重。",
            },
        ],
        "nodes": [
            "鲁史旧文：《春秋》原为鲁国史官的编年记录，记载鲁国及各国大事。",
            "孔子编订：孔子整理鲁史，将其编为教材，被尊为经典，称为《春秋经》。",
            "左氏传经：左丘明作《左传》，以详博的史实补充《春秋》简略的大纲。",
            "公羊解义：公羊高传《公羊传》，口耳相传，专阐《春秋》微言大义。",
            "穀梁别解：穀梁赤传《穀梁传》，与《公羊》相似而说法有别，形成另一解经传统。",
            "汉立博士：汉武帝设五经博士，《春秋》成为官方经典，三传各有博士传授。",
        ],
    },
    7: {
        "era_quote": "'四书五经'，是儒家的经典。四书是《大学》《中庸》《论语》《孟子》，是南宋朱熹编定的。",
        "positioning": "儒家核心经典，科举考试标准书目",
        "archive_summary": "四书指《大学》《中庸》《论语》《孟子》，由南宋朱熹编定并注释，称为'四书章句集注'。《大学》讲三纲领八条目，《中庸》讲人性本源，《论语》记孔子言行，《孟子》记孟子及其弟子言论。元明清三代以四书取士，影响极大。",
        "archive_impact": "四书成为元明清三代科举考试的标准书目，是中国读书人必读的教科书。其'修身齐家治国平天下'的理想，'仁''义''礼''智'的价值观，深深塑造了中国传统社会的伦理道德和政治文化。",
        "fragments": [
            ("南宋朱熹是宋代理学的集大成者，他将《大学》《中庸》《论语》《孟子》编在一起，加以注释，称为'四书章句集注'。", FragmentCategory.era),
            ("元明清三代都以四书取士，读书人从小就要读四书、背四书，参加科举考试要考四书。", FragmentCategory.era),
            ("朱熹，字元晦，号晦庵，是南宋著名的理学家、思想家、哲学家，被尊为朱子。", FragmentCategory.author),
            ("《大学》主要讲'三纲领''八条目'：明明德、亲民、止于至善；格物、致知、诚意、正心、修身、齐家、治国、平天下。", FragmentCategory.content),
            ("《论语》是孔子弟子及再传弟子记录的孔子言行录，全书二十篇，以语录体为主，内容涉及政治、伦理、教育等。", FragmentCategory.content),
            ("四书以语录体和对话体为主，文字平易流畅，深入浅出，比五经更容易为一般读者所接受。", FragmentCategory.style),
            ("四书中的'己所不欲，勿施于人''民为贵，社稷次之，君为轻'等思想，成为中国传统政治伦理的核心命题。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "四书是由哪位学者编定的？",
                "options": ["孔子", "孟子", "朱熹", "王阳明"],
                "correct_answer": "朱熹",
                "hint": "南宋理学的集大成者，他将四部书编在一起，加以注释。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "《大学》中的'八条目'不包括以下哪一项？",
                "options": ["格物", "致知", "中庸", "修身"],
                "correct_answer": "中庸",
                "hint": "八条目是格物、致知、诚意、正心、修身、齐家、治国、平天下。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "孟子提出了'______论''仁政说''民贵君轻'等主张。",
                "options": None,
                "correct_answer": "性善",
                "hint": "孟子认为人的本性是善良的，这与荀子的观点相反。",
            },
        ],
        "nodes": [
            "孔子讲学：孔子周游列国后设帐授徒，弟子记录其言行，编成《论语》。",
            "孟子继统：孟子继承孔子思想，游说诸侯，与弟子著书，形成《孟子》七篇。",
            "礼记成书：《大学》《中庸》作为《礼记》中的两篇，阐述儒家修身治国之道。",
            "朱熹编定：南宋朱熹将四书合编，作《四书章句集注》，确立四书体系。",
            "科举定式：元明清三代以四书取士，成为读书人必读的经典和考试标准。",
            "现代重估：近代以来对四书进行批判性继承，取其精华，去其糟粕。",
        ],
    },
    8: {
        "era_quote": "这时候出现了一批专门游说各国君主的策士。他们没有固定的职业，没有固定的国家，哪里有名利，就往哪里去。",
        "positioning": "战国策士言行录，纵横家思想宝库",
        "archive_summary": "《战国策》记载战国时期策士的游说之辞，全书分国编排，有东周、西周、秦、齐等十二国策，共三十三篇。策士们善于揣摩君主心理，投其所好，言辞铺张扬厉，气势充沛。这部书反映了战国时期的社会风貌和政治斗争。",
        "archive_impact": "《战国策》的铺张扬厉、善于运用寓言故事和比喻的文学风格，对后世的辞赋和散文产生了很大影响。它保存了大量战国时期的历史资料，是研究战国历史的重要史料。",
        "fragments": [
            ("战国时期，各国君主为富国强兵争相招揽人才，士的阶层大大活跃，形成了'百家争鸣'的局面。", FragmentCategory.era),
            ("战国后期秦国最强，东方六国较弱，主张六国联合抗秦的称为'合纵'，主张六国分别事秦的称为'连横'。", FragmentCategory.era),
            ("苏秦、张仪是战国最著名的纵横家，苏秦主张合纵，张仪主张连横，两人都以游说诸侯而显赫一时。", FragmentCategory.author),
            ("《战国策》全书分国编排，有东周、西周、秦、齐、楚、赵、魏、韩、燕、宋、卫、中山十二国策。", FragmentCategory.content),
            ("策士们的游说之辞善于揣摩君主心理，先讲故事或比喻引起兴趣，再提出主张，层层递进，引人入胜。", FragmentCategory.content),
            ("《战国策》的文章铺张扬厉，气势磅礴，善于运用寓言故事和比喻，极富感染力。", FragmentCategory.style),
            ("《战国策》对后世的辞赋和散文都有很大影响，汉代司马相如、扬雄等人的大赋继承了其铺张扬厉的风格。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "《战国策》全书分国编排，共包括多少国策？",
                "options": ["十国", "十二国", "七国", "十五国"],
                "correct_answer": "十二国",
                "hint": "包括东周、西周、秦、齐、楚、赵、魏、韩、燕、宋、卫、中山。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "战国时期主张六国联合抗秦的称为'合纵'，主张六国分别事秦的称为什么？",
                "options": ["连横", "纵横", "结盟", "附秦"],
                "correct_answer": "连横",
                "hint": "张仪是这一主张的代表人物，与苏秦的合纵相对。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "《战国策》是由西汉______整理编定的。",
                "options": None,
                "correct_answer": "刘向",
                "hint": "这位学者还整理了《说苑》《新序》等书，是西汉著名的文献学家。",
            },
        ],
        "nodes": [
            "士阶层兴起：春秋末年至战国，贵族没落，士阶层活跃，游说诸侯以求富贵。",
            "合纵连横：苏秦主张合纵抗秦，张仪主张连横事秦，纵横家学说风行一时。",
            "策士游说：策士凭三寸不烂之舌游说君主，言辞铺张扬厉，追求名利地位。",
            "史料杂采：秦汉间人杂采各国史料，记录策士言行，形成《战国策》初编。",
            "刘向编定：西汉刘向整理宫廷藏书，将杂乱的战国史料编定为三十三篇的《战国策》。",
            "文学影响：《战国策》的铺陈风格影响汉赋发展，成为后世散文和辞赋的重要源头。",
        ],
    },
    9: {
        "era_quote": "说起中国的史书，《史记》《汉书》，真是无人不知，无人不晓。这两部书，可以说是中国史书的祖宗。",
        "positioning": "纪传体史书的开山之作与断代史典范",
        "archive_summary": "《史记》是西汉司马迁作的纪传体通史，全书一百三十篇，记载从黄帝到汉武帝约三千年的历史。《汉书》是东汉班固作的纪传体断代史，只记西汉一代历史，体例大体依《史记》而改'书'为'志'。两部书代表了中国史学的两大传统。",
        "archive_impact": "《史记》被鲁迅誉为'史家之绝唱，无韵之《离骚》'，其纪传体例成为后世正史的标准体裁。《汉书》的'十志'详备地记述了汉代制度，开创了断代史的传统。两部书对中国史学和文学都产生了不可估量的影响。",
        "fragments": [
            ("司马迁的父亲司马谈是汉武帝时的太史令，有志于编修通史但未完成，临死嘱咐司马迁一定要完成。", FragmentCategory.era),
            ("班固的父亲班彪作《史记后传》，班固继承父业，在《史记后传》基础上编成《汉书》。", FragmentCategory.era),
            ("司马迁因替李陵辩护触怒汉武帝，被处以宫刑，他忍辱负重，完成了这部伟大的著作。", FragmentCategory.author),
            ("《史记》是中国第一部纪传体通史，分为本纪、表、书、世家、列传五体，以人物为中心。", FragmentCategory.content),
            ("《汉书》是中国第一部纪传体断代史，只记西汉一代，改'书'为'志'，改'世家'为'列传'。", FragmentCategory.content),
            ("《史记》文字生动活泼，富于感情，善于刻画人物；《汉书》文字严谨整饬，不如《史记》生动。", FragmentCategory.style),
            ("鲁迅赞誉《史记》为'史家之绝唱，无韵之《离骚》'，高度评价其史学和文学价值。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "《史记》分为哪五体？",
                "options": ["风、雅、颂、赋、比", "本纪、表、书、世家、列传", "典、谟、训、诰、誓", "纪、传、志、表、书"],
                "correct_answer": "本纪、表、书、世家、列传",
                "hint": "本纪记帝王，表是年表，书记制度，世家记诸侯，列传记重要人物。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "《汉书》与《史记》相比，体例上有什么主要变化？",
                "options": ["改'书'为'志'，改'世家'为'列传'", "增加了'表'的数量", "删除了'本纪'", "将'列传'改为'世家'"],
                "correct_answer": "改'书'为'志'，改'世家'为'列传'",
                "hint": "《汉书》只记西汉一代，体例大体依照《史记》但有所调整。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "鲁迅赞誉《史记》为'史家之绝唱，无韵之《______》'。",
                "options": None,
                "correct_answer": "离骚",
                "hint": "这是屈原的代表作，鲁迅以此赞誉《史记》的文学价值。",
            },
        ],
        "nodes": [
            "司马谈遗志：司马谈任太史令，有志编修通史，临终嘱咐司马迁继承遗志。",
            "司马迁著史：司马迁继承父业，遭宫刑后忍辱负重，完成《史记》一百三十篇。",
            "班彪续写：班彪认为《史记》止于汉武帝，作《史记后传》以续西汉历史。",
            "班固成书：班固奉诏修史，在父业基础上编成《汉书》，开创断代史体例。",
            "史汉并称：《史记》《汉书》并称，代表通史与断代史两大传统。",
            "千载流芳：两部书成为后世正史典范，影响中国史学两千余年。",
        ],
    },
    10: {
        "era_quote": "春秋末年，封建制度开始崩坏，贵族的统治权渐渐维持不住了……形成了'百家争鸣'的局面。",
        "positioning": "春秋战国思想精华，中国哲学的源头活水",
        "archive_summary": "诸子百家是春秋战国时期各种学派的统称，最重要的有儒、道、墨、法、名、阴阳六家。儒家以孔子为宗师，主张仁义礼智信；道家以老子、庄子为代表，主张无为而治；墨家主张兼爱非攻；法家主张以法治国；名家善辩名实；阴阳家讲五行之说。",
        "archive_impact": "诸子百家的学说奠定了中国古代思想的基础，儒家成为后世正统，道家影响哲学和宗教，法家影响政治制度，墨家影响科技和社会思想。这些学说互相辩难又互相吸收，共同构成了中华文化的思想根基。",
        "fragments": [
            ("春秋末年封建制度崩坏，贵族没落，平民中有本领的爬了起来，到了战国，各国君主争相招揽人才。", FragmentCategory.era),
            ("战国时期的士阶层周游列国，游说君主，互相辩论攻击，形成了'百家争鸣'的繁荣局面。", FragmentCategory.era),
            ("孔子名丘，字仲尼，春秋末期鲁国人，是儒家学派创始人，被后世尊为'至圣先师'。", FragmentCategory.author),
            ("儒家以孔子为宗师，主张'仁''义''礼''智''信'，强调道德修养和社会责任。", FragmentCategory.content),
            ("墨家是墨翟创立的，主张'兼爱''非攻''尚贤''节用'，是一个有组织的团体，首领称为'钜子'。", FragmentCategory.content),
            ("诸子散文各具特色：《论语》语录体平易，《孟子》对话体雄辩，《庄子》寓言体恣肆，《韩非子》论说体犀利。", FragmentCategory.style),
            ("诸子百家共同奠定了中国古代思想的基础，其学说互相辩难又互相吸收，构成中华文化的思想根基。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "诸子百家中，主张'兼爱''非攻'的是哪一家？",
                "options": ["儒家", "道家", "墨家", "法家"],
                "correct_answer": "墨家",
                "hint": "这一学派由墨翟创立，反对战争，主张普遍的爱。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "法家的集大成者是谁？",
                "options": ["商鞅", "李斯", "韩非", "管仲"],
                "correct_answer": "韩非",
                "hint": "他主张'法''术''势'三者并用，是法家思想的总结者。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "道家以老子、______为代表，主张无为而治。",
                "options": None,
                "correct_answer": "庄子",
                "hint": "这位战国时期的思想家继承老子，强调精神自由，文章汪洋恣肆。",
            },
        ],
        "nodes": [
            "礼崩乐坏：春秋末年封建制度瓦解，旧秩序崩溃，为新思想产生创造条件。",
            "孔子创儒：孔子提出仁学，周游列国传播思想，弟子编《论语》，儒家兴起。",
            "老子论道：老子著《道德经》，提出无为而治，道家思想开始流传。",
            "百家争鸣：战国时儒、道、墨、法、名、阴阳等学派互相辩难，思想空前繁荣。",
            "秦汉整合：秦始皇重法家，汉初尊黄老，汉武帝独尊儒术，思想逐渐统一。",
            "千古传承：诸子思想融入中华文化血脉，影响中国社会的方方面面。",
        ],
    },
    11: {
        "era_quote": "屈原因遭谗言，被楚怀王放逐。他心中忧愤，写下了《离骚》。",
        "positioning": "浪漫主义诗歌源头，汉代文学代表",
        "archive_summary": "屈原被楚怀王放逐，写下《离骚》，全诗三百七十多句，是中国古代最长的抒情诗。屈原的作品后人合称为'楚辞'，具有浓厚的地方色彩。宋玉是屈原之后的楚辞作家。到了汉代，楚辞演变成'赋'，司马相如、扬雄、班固、张衡是汉赋代表作家。",
        "archive_impact": "屈原的《离骚》开创了中国浪漫主义的文学传统，'香草美人'的象征手法影响深远。汉赋铺张扬厉的风格成为汉代文学的代表，对后世的骈文和诗歌都产生了重要影响。",
        "fragments": [
            ("屈原是战国时期楚国贵族，因遭谗言被楚怀王放逐，心中忧愤，写下了《离骚》等作品。", FragmentCategory.era),
            ("汉代设立乐府，采集各地歌谣，楚辞在这种文化环境中演变成'赋'，成为汉代文学的代表。", FragmentCategory.era),
            ("屈原，名平，字原，是楚国贵族，曾任左徒、三闾大夫，是中国文学史上第一位伟大诗人。", FragmentCategory.author),
            ("《离骚》全诗三百七十多句，两千四百多字，叙述了诗人的身世、抱负和遭遇，是中国古代最长的抒情诗。", FragmentCategory.content),
            ("汉赋继承了楚辞的铺张扬厉，但更加讲究排比对偶，内容多描写宫殿、都城、田猎等，以显示帝国富庶。", FragmentCategory.content),
            ("《离骚》运用了丰富的想象和夸张，创造了'香草美人'的象征手法，语言华美典雅，节奏鲜明。", FragmentCategory.style),
            ("屈原开创了中国浪漫主义的文学传统，对后世诗歌产生了深远影响，李白、李贺等都深受其影响。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "《离骚》的作者是谁？",
                "options": ["宋玉", "屈原", "司马相如", "李白"],
                "correct_answer": "屈原",
                "hint": "这位楚国贵族因遭谗言被放逐，写下了中国古代最长的抒情诗。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "汉赋的代表作家中，以《子虚赋》《上林赋》著称的是谁？",
                "options": ["扬雄", "班固", "司马相如", "张衡"],
                "correct_answer": "司马相如",
                "hint": "他是西汉最著名的赋作家，其赋铺张扬厉，是汉赋的典范。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "屈原在《离骚》中创造了'______美人'的象征手法，用香花芳草比喻高洁的品质。",
                "options": None,
                "correct_answer": "香草",
                "hint": "这种以芬芳植物象征美好品德的手法，成为后世诗歌的重要传统。",
            },
        ],
        "nodes": [
            "屈原放逐：屈原因遭谗言被楚怀王放逐，忧愤而作《离骚》，开创楚辞体。",
            "楚辞形成：屈原作《离骚》《九歌》等，宋玉继之，形成具有楚地特色的楚辞传统。",
            "汉赋兴起：汉代楚辞演变为赋，铺陈华美，成为汉代文学的代表体裁。",
            "相如杰作：司马相如作《子虚赋》《上林赋》，将汉赋推向艺术高峰。",
            "班张继作：班固《两都赋》、张衡《二京赋》，以赋写都城，规模宏大。",
            "小赋革新：东汉末年抒情小赋兴起，篇幅短小，情感真挚，开骈赋先河。",
        ],
    },
    12: {
        "era_quote": "汉武帝立乐府，采集代、赵、秦、楚的歌谣和乐谱……这些歌谣，后来称为'乐府诗'。",
        "positioning": "从汉乐府到唐诗宋词，中国诗歌的灿烂长河",
        "archive_summary": "汉武帝立乐府采集歌谣，形成乐府诗。汉末五言诗兴起，《古诗十九首》是五言诗的冠冕。魏晋时期有'建安风骨'和陶渊明田园诗。唐代诗歌达到顶峰，李白、杜甫是两大巨星。宋代是词的盛世，苏轼、辛弃疾是代表词人。诗、词、曲一脉相承，构成中国古典诗歌的灿烂长河。",
        "archive_impact": "中国古典诗歌从《诗经》的现实主义到屈原的浪漫主义，从汉乐府的民间情怀到唐诗的格律精严，从宋词的婉约豪放到元曲的通俗自然，形成了世界文学史上独一无二的诗歌传统，影响东亚文化圈数千年。",
        "fragments": [
            ("汉武帝立乐府，采集各地歌谣和乐谱，教李延年作协律都尉负责整理，当时搜集的歌谣共有一百三十八家。", FragmentCategory.era),
            ("宋代是词的盛世，柳永、苏轼、辛弃疾、李清照等词人辈出，词成为宋代文学的代表。", FragmentCategory.era),
            ("曹操、曹丕、曹植父子三人都是杰出的诗人，他们的诗风格刚健有力，慷慨悲凉，后人称为'建安风骨'。", FragmentCategory.author),
            ("《古诗十九首》是五言诗的最早杰作，作者不详，内容大多是游子思妇的离愁别绪，被刘勰誉为'五言之冠冕'。", FragmentCategory.content),
            ("唐代诗人辈出，李白诗豪放飘逸，是浪漫主义代表；杜甫诗沉郁顿挫，是现实主义代表；白居易提倡新乐府运动。", FragmentCategory.content),
            ("杜甫的诗反映现实，被称为'诗史'；李白的诗想象丰富，被称为'诗仙'，两人并称'李杜'。", FragmentCategory.style),
            ("诗到唐代达到顶峰，宋人另辟蹊径发展词体，词到宋代也达到顶峰，元代曲又兴起，诗、词、曲一脉相承。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "被刘勰誉为'五言之冠冕'的是哪部作品？",
                "options": ["《诗经》", "《古诗十九首》", "《乐府诗集》", "《楚辞》"],
                "correct_answer": "《古诗十九首》",
                "hint": "这是东汉末年文人所作的五言诗，语言朴素自然，情感真挚深沉。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "宋代词人中，属于豪放派代表的是谁？",
                "options": ["柳永", "李清照", "苏轼", "晏殊"],
                "correct_answer": "苏轼",
                "hint": "他扩大了词的题材，提高了词的意境，使词成为独立的抒情诗体。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "白居易提倡'新乐府运动'，主张'文章合为时而著，歌诗合为______而作'。",
                "options": None,
                "correct_answer": "事",
                "hint": "他强调诗歌应该反映现实，为具体的事件和社会问题而创作。",
            },
        ],
        "nodes": [
            "汉乐府兴：汉武帝立乐府采集歌谣，感于哀乐，缘事而发，开创乐府传统。",
            "五言成熟：《古诗十九首》标志文人五言诗成熟，语言朴素，情感深沉。",
            "建安风骨：曹操父子与建安七子，诗风慷慨悲凉，刚健有力。",
            "陶潜田园：陶渊明辞官归隐，开创田园诗派，诗风平淡自然。",
            "唐诗巅峰：李白、杜甫双峰并峙，近体诗格律精严，诗歌达到历史高峰。",
            "宋词盛世：苏轼、辛弃疾豪放，柳永、李清照婉约，词成为宋代文学代表。",
        ],
    },
    13: {
        "era_quote": "现存的中国最早的文，是商代的卜辞。这是甲骨上的文字，是史官占卜的记录。",
        "positioning": "从先秦散文到唐宋古文，中国散文发展脉络",
        "archive_summary": "中国散文从商代卜辞开始，历经《尚书》的记言、先秦历史散文和诸子散文的繁荣，汉代司马迁《史记》达到高峰。魏晋出现骈文，唐代韩愈、柳宗元提倡古文运动，宋代欧阳修、苏轼继续发扬，使古文成为文坛主流。明清散文流派众多，但总体成就不如唐宋。",
        "archive_impact": "中国散文的发展历程体现了文学形式与内容的不断变革。古文运动反对骈文的空洞形式，主张恢复先秦两汉的散文传统，对后世散文创作产生了深远影响。桐城派等流派延续了古文的传统，直到近代白话文运动兴起。",
        "fragments": [
            ("商代的卜辞是现存中国最早的文，是甲骨上的文字，是史官占卜的记录，已具备叙事和记言的成分。", FragmentCategory.era),
            ("唐代韩愈、柳宗元提倡古文运动，反对骈文；宋代欧阳修、苏轼继续提倡，使古文成为文坛主流。", FragmentCategory.era),
            ("韩愈，字退之，唐代文学家、思想家，古文运动的领袖，主张'惟陈言之务去'，强调文章独创性。", FragmentCategory.author),
            ("先秦散文分为历史散文和诸子散文两大类，历史散文以《左传》《国语》《战国策》为代表。", FragmentCategory.content),
            ("汉代司马迁的《史记》具有很高的文学价值，文字生动活泼，富于感情，是汉代散文的巅峰。", FragmentCategory.content),
            ("苏轼的散文挥洒自如，妙趣横生，达到了古文的最高境界，与欧阳修并称'欧苏'。", FragmentCategory.style),
            ("古文运动反对骈文的空洞形式，主张恢复先秦两汉的散文传统，对后世散文创作影响深远。", FragmentCategory.impact),
        ],
        "diagnostics": [
            {
                "question_type": QuestionType.choice,
                "content": "唐代古文运动的领袖是哪两位文学家？",
                "options": ["李白、杜甫", "韩愈、柳宗元", "欧阳修、苏轼", "王安石、曾巩"],
                "correct_answer": "韩愈、柳宗元",
                "hint": "他们反对骈文，主张恢复先秦两汉的散文传统。",
            },
            {
                "question_type": QuestionType.choice,
                "content": "骈文又叫什么？",
                "options": ["古文", "散文", "四六文", "辞赋"],
                "correct_answer": "四六文",
                "hint": "骈文讲究对偶，四字六字相间，因此得名。",
            },
            {
                "question_type": QuestionType.fill_blank,
                "content": "韩愈主张写文章要有独创性，提出'惟______之务去'。",
                "options": None,
                "correct_answer": "陈言",
                "hint": "意思是务必去掉陈旧的言辞，追求创新。",
            },
        ],
        "nodes": [
            "甲骨卜辞：商代史官占卜记录，是现存最早的散文雏形。",
            "尚书记言：中国最古的记言历史，文字古朴，奠定散文基础。",
            "先秦繁荣：《左传》《战国策》等历史散文与诸子散文交相辉映。",
            "史记巅峰：司马迁《史记》文字生动，是汉代散文的最高成就。",
            "骈文兴起：魏晋南北朝骈文讲究对偶，形式华美但束缚思想。",
            "古文复兴：唐宋古文运动反对骈文，恢复先秦两汉散文传统，成就辉煌。",
        ],
    },
}


def seed_restoration_data(db: Session):
    if db.query(RestorationChapter).first():
        print("Restoration data already seeded, skipping.")
        return

    for meta in chapters_metadata:
        data = CHAPTERS_DATA[meta["chapter_id"]]
        chapter = RestorationChapter(
            chapter_id=meta["chapter_id"],
            name=meta["name"],
            alias=meta["alias"],
            description=meta["description"],
            difficulty=Difficulty(meta["difficulty"]),
            sort_order=meta["chapter_id"],
            era_quote=data["era_quote"],
            positioning=data["positioning"],
            archive_summary=data["archive_summary"],
            archive_impact=data["archive_impact"],
        )
        db.add(chapter)
        db.flush()

        # Fragments
        for idx, (content, category) in enumerate(data["fragments"]):
            db.add(RestorationFragment(
                chapter_id=chapter.id,
                content=content,
                category=category,
                sort_order=idx,
            ))

        # Diagnostics
        for idx, diag in enumerate(data["diagnostics"]):
            db.add(RestorationDiagnostic(
                chapter_id=chapter.id,
                question_type=diag["question_type"],
                content=diag["content"],
                options=diag["options"],
                correct_answer=diag["correct_answer"],
                hint=diag["hint"],
                sort_order=idx,
            ))

        # Nodes
        for idx, node_content in enumerate(data["nodes"]):
            db.add(RestorationNode(
                chapter_id=chapter.id,
                content=node_content,
                correct_order=idx + 1,
                sort_order=idx,
            ))

    db.commit()
    print(f"Seeded {len(chapters_metadata)} restoration chapters.")
